lib/platform_web/router.ex
defmodule PlatformWeb.Router do
  use PlatformWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlatformWeb.PlayerAuthController, repo: Platform.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PlatformWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/players", PlayerController
    resources "/sessions", PlayerSessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  scope "/api", PlatformWeb do
    pipe_through :api

    resources "/players", PlayerApiController, except: [:new, :edit]
    resources "/games", GameController, except: [:new, :edit]
    resources "/gameplays", GameplayController, except: [:new, :edit]
  end
end

lib/platform_web/views/layout_view.ex
defmodule PlatformWeb.LayoutView do
  use PlatformWeb, :view
end

lib/platform_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Platform · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">          
          <ul>
            <%= if @current_user do %>
              <p>Angemeldet als <strong><%= @current_user.username %></strong></p>
              <%= link "Abmelden", to: Routes.player_session_path(@conn, :delete, @current_user), method: :delete, class: "button" %>
            <% else %>
                <%= link "Registrieren", to: Routes.player_path(@conn, :new), class: "button" %>
                <%= link "Anmelden", to: Routes.player_session_path(@conn, :new), class: "button" %>
            <% end %>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>